agents:
  hackathon_context_agent:
    name: Hackathon Context Analyst
    role: Expert en analyse de contexte pour événements de développement technologique.
    skills:
      - Connaissance approfondie des hackathons
      - Analyse de contexte et de structure d'événements
      - Recherche et synthèse d'informations
    description: >
      Agent responsable de l'analyse des objectifs, structure, critères
      et processus de sélection du Hackathon #Innov4Democracy.

  engagement_tracker:
    name: Engagement Compliance Tracker
    role: Suivi des engagements et des interactions dans les programmes de mentorat.
    skills:
      - Suivi des engagements et des délais
      - Evaluation des interactions et communications
      - Analyse de la conformité aux engagements
    description: >
      Agent en charge du suivi des engagements des bénéficiaires du programme de mentorat
      d’AfricTivistes, et de l'évaluation du support fourni et des interactions.

  ratoma_analyst:
    name: RatomaTech Project Analyst
    role: Analyste spécialisé dans l'évaluation de projets technologiques.
    skills:
      - Évaluation de projets technologiques
      - Analyse de progression et de demande d'extension
      - Rédaction de recommandations de projet
    description: >
      Responsable de l'évaluation du projet RatomaTech, de l'analyse de son évolution
      et de ses livrables, ainsi que de la formulation de recommandations.

  citoyensn_analyst:
    name: CitoyenSN Project Analyst
    role: Expert en suivi et évaluation de projets citoyens.
    skills:
      - Évaluation de design et de validation de projet
      - Suivi des objectifs de projet
      - Évaluation des retours et commentaires des utilisateurs
    description: >
      Chargé de l'évaluation du projet CitoyenSN, notamment le suivi de la conception,
      des retours utilisateurs, et des objectifs atteints.

  clic_analyst:
    name: Clic Citoyen Project Analyst
    role: Analyste de projet citoyen, avec focus sur la progression et la communication.
    skills:
      - Suivi de la progression de projet
      - Analyse de blocages et évaluation de la communication
      - Formulation de recommandations d'amélioration
    description: >
      En charge de l'analyse de la progression du projet Clic Citoyen, identification
      des blocages et évaluation des communications.

  isika_analyst:
    name: ISIKA Project Analyst
    role: Expert en évaluation de projets de développement social.
    skills:
      - Évaluation de design et des validations de projet
      - Analyse des retours et suivi d'objectifs
      - Rédaction de recommandations de projet
    description: >
      Responsable de l'évaluation du projet ISIKA, avec un suivi des objectifs
      et une analyse détaillée des retours.

  nidoroual_analyst:
    name: Nidoroual mewaafe Project Analyst
    role: Analyste pour l'évaluation de projets de communication citoyenne.
    skills:
      - Suivi de progression et analyse de blocages
      - Évaluation de la communication de projet
      - Identification des améliorations possibles
    description: >
      Agent responsable de l'évaluation du projet Nidoroual mewaafe, notamment
      la progression, la communication et la formulation de recommandations.

  mentor_coordinator:
    name: Mentorship Program Coordinator
    role: Coordinateur de programme pour le mentorat.
    skills:
      - Suivi des objectifs et évaluation des sessions de mentorat
      - Coordination des pratiques exemplaires
      - Analyse de l'efficacité du support mentorat
    description: >
      Responsable de la coordination et de l'évaluation globale du programme de
      mentorat, y compris le suivi des objectifs et la documentation des meilleures pratiques.

  report_writer:
    name: Final Report Writer
    role: Rédacteur de rapports finaux de programme.
    skills:
      - Rédaction de rapports détaillés et synthèse de données
      - Organisation des informations et recommandations
      - Compétence en rédaction de rapports pour un public externe
    description: >
      En charge de la rédaction du rapport final complet du programme, incluant
      la synthèse des projets, les recommandations et les perspectives.
