tasks:
  context_analysis:
    description: >
      Analyser le contexte global du Hackathon #Innov4Democracy,
      incluant :
      1. Objectifs du Charter Project Africa
      2. Structure du hackathon
      3. Processus de sélection
      4. Critères d'évaluation
    expected_output: >
      Résumé des points clés du contexte du hackathon, incluant les
      objectifs, la structure, le processus de sélection et les critères d'évaluation.
    agent: hackathon_context_agent
    dependencies: []

  engagement_analysis:
    description: |
      Analyser le respect des engagements dans le mentorat AfricTivistes :
      1. Suivi des engagements des bénéficiaires
      2. Évaluation du support fourni par AfricTivistes
      3. Analyse des interactions et de la communication
      4. Respect des délais et des livrables
    expected_output: >
      Analyse complète des engagements des bénéficiaires, avec des
      recommandations et un rapport sur la communication, le respect des délais et les livrables.
    agent: engagement_tracker
    dependencies: ["context_analysis"]

  ratoma_evaluation:
    description: |
      Évaluer le projet RatomaTech, en se focalisant sur :
      1. Analyse de l'évolution du projet
      2. Demande d'extension
      3. Analyse des livrables et de la plateforme
      4. Recommandations spécifiques
    expected_output: >
      Rapport détaillé de l'évolution et des livrables du projet RatomaTech, 
      incluant des recommandations pour la demande d'extension et l'analyse des livrables.
    agent: ratoma_analyst
    dependencies: ["engagement_analysis"]

  citoyensn_evaluation:
    description: |
      Évaluer le projet CitoyenSN :
      1. Analyse du design et des validations
      2. Évaluation des retours et commentaires
      3. Suivi des objectifs
      4. Recommandations spécifiques
    expected_output: >
      Rapport d'évaluation détaillé pour CitoyenSN avec une analyse du design, des
      commentaires reçus et des recommandations d'amélioration.
    agent: citoyensn_analyst
    dependencies: ["engagement_analysis"]

  clic_evaluation:
    description: |
      Évaluer le projet Clic Citoyen :
      1. Analyse de la progression
      2. Identification des blocages
      3. Évaluation des communications
      4. Recommandations spécifiques
    expected_output: >
      Rapport sur Clic Citoyen, documentant la progression, les blocages, et les recommandations.
    agent: clic_analyst
    dependencies: ["engagement_analysis"]

  isika_evaluation:
    description: |
      Évaluer le projet ISIKA :
      1. Analyse du design et des validations
      2. Évaluation des retours et commentaires
      3. Suivi des objectifs
      4. Recommandations spécifiques
    expected_output: >
      Évaluation du projet ISIKA, avec un suivi des objectifs et une analyse des retours.
    agent: isika_analyst
    dependencies: ["engagement_analysis"]

  nidoroual_evaluation:
    description: |
      Évaluer le projet Nidoroual mewaafe :
      1. Analyse de la progression
      2. Identification des blocages
      3. Évaluation des communications
      4. Recommandations spécifiques
    expected_output: >
      Évaluation de Nidoroual mewaafe avec un rapport des blocages et des actions proposées.
    agent: nidoroual_analyst
    dependencies: ["engagement_analysis"]

  mentoring_coordination:
    description: |
      Coordonner et évaluer le programme de mentorat :
      1. Analyse de l'efficacité du support fourni
      2. Évaluation des sessions de mentorat
      3. Suivi des objectifs globaux
      4. Identification des meilleures pratiques
    expected_output: >
      Synthèse sur la coordination et l'efficacité du programme de mentorat,
      incluant des meilleures pratiques et recommandations.
    agent: mentor_coordinator
    dependencies: [
      "ratoma_evaluation",
      "citoyensn_evaluation",
      "clic_evaluation",
      "isika_evaluation",
      "nidoroual_evaluation"
    ]

  final_report:
    description: |
      Rédiger le rapport final complet sur le programme de mentorat :
      1. Synthèse du contexte et des objectifs
      2. Analyse détaillée de chaque projet
      3. Évaluation globale du programme
      4. Recommandations et perspectives
    expected_output: >
      Rapport final du programme avec une synthèse des projets, des recommandations,
      et une analyse des perspectives.
    agent: report_writer
    dependencies: ["mentoring_coordination"]
    output_file: mentorat_final_report.md
